definitions:
  entity.Categories:
    properties:
      categoryId:
        type: integer
      categoryName:
        type: string
      description:
        type: string
      picture:
        items:
          type: integer
        type: array
    type: object
info:
  contact: {}
paths:
  /api/categories/{id}:
    get:
      consumes:
      - application/json
      description: get category
      parameters:
      - description: category_id
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Categories'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Category
      tags:
      - categories
swagger: "2.0"
